<?php
# Generated by the protocol buffer compiler (https://github.com/mix-php/grpc). DO NOT EDIT!
# source: xindalu.proto

namespace Votes;

use Mix\Grpc;
use Mix\Grpc\Context;

class PaySvcClient extends Grpc\Client\AbstractClient
{
    /**
    * @param Context $context
    * @param ArgsGetPayInfo $request
    * @param array $options
    * @return ReplyGetPayinfo
    *
    * @throws Grpc\Exception\InvokeException
    */
    public function GetInfo(Context $context, ArgsGetPayInfo $request): ReplyGetPayinfo
    {
        return $this->_simpleRequest('/votes.PaySvc/GetInfo', $context, $request, new ReplyGetPayinfo());
    }
}
