<?php
# Generated by the protocol buffer compiler (https://github.com/mix-php/grpc). DO NOT EDIT!
# source: votes.proto

namespace Votes;

use Mix\Grpc;
use Mix\Grpc\Context;

class VotesClient extends Grpc\Client\AbstractClient
{
    /**
    * @param Context $context
    * @param EnrollInfoReq $request
    * @param array $options
    * @return EnrollResp
    *
    * @throws Grpc\Exception\InvokeException
    */
    public function GetEnrollInfo(Context $context, EnrollInfoReq $request): EnrollResp
    {
        return $this->_simpleRequest('/votes.Votes/GetEnrollInfo', $context, $request, new EnrollResp());
    }

    /**
    * @param Context $context
    * @param ActidReq $request
    * @param array $options
    * @return EnrollListResp
    *
    * @throws Grpc\Exception\InvokeException
    */
    public function GetEnrollList(Context $context, ActidReq $request): EnrollListResp
    {
        return $this->_simpleRequest('/votes.Votes/GetEnrollList', $context, $request, new EnrollListResp());
    }

    /**
    * @param Context $context
    * @param ActInfoReq $request
    * @param array $options
    * @return ActInfoResp
    *
    * @throws Grpc\Exception\InvokeException
    */
    public function GetActivityInfo(Context $context, ActInfoReq $request): ActInfoResp
    {
        return $this->_simpleRequest('/votes.Votes/GetActivityInfo', $context, $request, new ActInfoResp());
    }

    /**
    * @param Context $context
    * @param EnrollReq $request
    * @param array $options
    * @return EnrollResp
    *
    * @throws Grpc\Exception\InvokeException
    */
    public function Enroll(Context $context, EnrollReq $request): EnrollResp
    {
        return $this->_simpleRequest('/votes.Votes/Enroll', $context, $request, new EnrollResp());
    }

    /**
    * @param Context $context
    * @param VotesReq $request
    * @param array $options
    * @return VotesResp
    *
    * @throws Grpc\Exception\InvokeException
    */
    public function Votes(Context $context, VotesReq $request): VotesResp
    {
        return $this->_simpleRequest('/votes.Votes/Votes', $context, $request, new VotesResp());
    }

    /**
    * @param Context $context
    * @param ActInfoReq $request
    * @param array $options
    * @return ActInfoResp
    *
    * @throws Grpc\Exception\InvokeException
    */
    public function IncrActiviView(Context $context, ActInfoReq $request): ActInfoResp
    {
        return $this->_simpleRequest('/votes.Votes/IncrActiviView', $context, $request, new ActInfoResp());
    }
}
