<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: votes.proto

namespace GPBMetadata;

class Votes
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            '
¶
votes.protovotes"J
ActidReq
actid (
limit (2.votes.LimitReq
keyword (	"

ActInfoReq
actid ("(
LimitReq
offset (
size (",
EnrollInfoReq
aeid (
actid ("ê
	EnrollReq
auid (
beid (
ptyid (
uid (
name (	
address (	
images (	
descr (	
actid	 ("≈

EnrollResp
auid (
beid (
ptyid (
uid (
name (	
address (	
images (	
descr (	
	votecount	 (
	viewcount
 (
aeid (
actid ("1
EnrollListResp
data (2.votes.EnrollResp"k
VotesReq
auid (
beid (
ptyid (
uid (
actid (
aeid (

ip (	"Ö
	VotesResp
auid (
beid (
ptyid (
uid (
avid (
aeid (
	votecount (
	viewcount ("¯
ActInfoResp
actid (
beid (
ptyid (
title (	
descr (	
status (

start_date (
enroll_date (
end_date	 (
	votecount
 (
	viewcount (
type (
num (
enrollcount (2»
Votes8
GetEnrollInfo.votes.EnrollInfoReq.votes.EnrollResp7
GetEnrollList.votes.ActidReq.votes.EnrollListResp8
GetActivityInfo.votes.ActInfoReq.votes.ActInfoResp-
Enroll.votes.EnrollReq.votes.EnrollResp*
Votes.votes.VotesReq.votes.VotesResp7
IncrActiviView.votes.ActInfoReq.votes.ActInfoRespbproto3'
        , true);

        static::$is_initialized = true;
    }
}

