<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: votes.proto

namespace Votes;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>votes.ActidReq</code>
 */
class ActidReq extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int64 actid = 1;</code>
     */
    protected $actid = 0;
    /**
     * Generated from protobuf field <code>.votes.LimitReq limit = 2;</code>
     */
    protected $limit = null;
    /**
     * Generated from protobuf field <code>string keyword = 3;</code>
     */
    protected $keyword = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $actid
     *     @type \Votes\LimitReq $limit
     *     @type string $keyword
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Votes::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int64 actid = 1;</code>
     * @return int|string
     */
    public function getActid()
    {
        return $this->actid;
    }

    /**
     * Generated from protobuf field <code>int64 actid = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setActid($var)
    {
        GPBUtil::checkInt64($var);
        $this->actid = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.votes.LimitReq limit = 2;</code>
     * @return \Votes\LimitReq|null
     */
    public function getLimit()
    {
        return $this->limit;
    }

    public function hasLimit()
    {
        return isset($this->limit);
    }

    public function clearLimit()
    {
        unset($this->limit);
    }

    /**
     * Generated from protobuf field <code>.votes.LimitReq limit = 2;</code>
     * @param \Votes\LimitReq $var
     * @return $this
     */
    public function setLimit($var)
    {
        GPBUtil::checkMessage($var, \Votes\LimitReq::class);
        $this->limit = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string keyword = 3;</code>
     * @return string
     */
    public function getKeyword()
    {
        return $this->keyword;
    }

    /**
     * Generated from protobuf field <code>string keyword = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setKeyword($var)
    {
        GPBUtil::checkString($var, True);
        $this->keyword = $var;

        return $this;
    }

}

