<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: votes.proto

namespace Votes;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 *返回活动信息
 *
 * Generated from protobuf message <code>votes.ActInfoResp</code>
 */
class ActInfoResp extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int64 actid = 1;</code>
     */
    protected $actid = 0;
    /**
     * Generated from protobuf field <code>int64 beid = 2;</code>
     */
    protected $beid = 0;
    /**
     * Generated from protobuf field <code>int64 ptyid = 3;</code>
     */
    protected $ptyid = 0;
    /**
     * Generated from protobuf field <code>string title = 4;</code>
     */
    protected $title = '';
    /**
     * Generated from protobuf field <code>string descr = 5;</code>
     */
    protected $descr = '';
    /**
     * Generated from protobuf field <code>int64 status = 6;</code>
     */
    protected $status = 0;
    /**
     * Generated from protobuf field <code>int64 start_date = 7;</code>
     */
    protected $start_date = 0;
    /**
     * Generated from protobuf field <code>int64 enroll_date = 8;</code>
     */
    protected $enroll_date = 0;
    /**
     * Generated from protobuf field <code>int64 end_date = 9;</code>
     */
    protected $end_date = 0;
    /**
     * Generated from protobuf field <code>int64 votecount = 10;</code>
     */
    protected $votecount = 0;
    /**
     * Generated from protobuf field <code>int64 viewcount = 11;</code>
     */
    protected $viewcount = 0;
    /**
     * Generated from protobuf field <code>int64 type = 12;</code>
     */
    protected $type = 0;
    /**
     * Generated from protobuf field <code>int64 num = 13;</code>
     */
    protected $num = 0;
    /**
     * Generated from protobuf field <code>int64 enrollcount = 14;</code>
     */
    protected $enrollcount = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $actid
     *     @type int|string $beid
     *     @type int|string $ptyid
     *     @type string $title
     *     @type string $descr
     *     @type int|string $status
     *     @type int|string $start_date
     *     @type int|string $enroll_date
     *     @type int|string $end_date
     *     @type int|string $votecount
     *     @type int|string $viewcount
     *     @type int|string $type
     *     @type int|string $num
     *     @type int|string $enrollcount
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Votes::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int64 actid = 1;</code>
     * @return int|string
     */
    public function getActid()
    {
        return $this->actid;
    }

    /**
     * Generated from protobuf field <code>int64 actid = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setActid($var)
    {
        GPBUtil::checkInt64($var);
        $this->actid = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 beid = 2;</code>
     * @return int|string
     */
    public function getBeid()
    {
        return $this->beid;
    }

    /**
     * Generated from protobuf field <code>int64 beid = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setBeid($var)
    {
        GPBUtil::checkInt64($var);
        $this->beid = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 ptyid = 3;</code>
     * @return int|string
     */
    public function getPtyid()
    {
        return $this->ptyid;
    }

    /**
     * Generated from protobuf field <code>int64 ptyid = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setPtyid($var)
    {
        GPBUtil::checkInt64($var);
        $this->ptyid = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string title = 4;</code>
     * @return string
     */
    public function getTitle()
    {
        return $this->title;
    }

    /**
     * Generated from protobuf field <code>string title = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setTitle($var)
    {
        GPBUtil::checkString($var, True);
        $this->title = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string descr = 5;</code>
     * @return string
     */
    public function getDescr()
    {
        return $this->descr;
    }

    /**
     * Generated from protobuf field <code>string descr = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setDescr($var)
    {
        GPBUtil::checkString($var, True);
        $this->descr = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 status = 6;</code>
     * @return int|string
     */
    public function getStatus()
    {
        return $this->status;
    }

    /**
     * Generated from protobuf field <code>int64 status = 6;</code>
     * @param int|string $var
     * @return $this
     */
    public function setStatus($var)
    {
        GPBUtil::checkInt64($var);
        $this->status = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 start_date = 7;</code>
     * @return int|string
     */
    public function getStartDate()
    {
        return $this->start_date;
    }

    /**
     * Generated from protobuf field <code>int64 start_date = 7;</code>
     * @param int|string $var
     * @return $this
     */
    public function setStartDate($var)
    {
        GPBUtil::checkInt64($var);
        $this->start_date = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 enroll_date = 8;</code>
     * @return int|string
     */
    public function getEnrollDate()
    {
        return $this->enroll_date;
    }

    /**
     * Generated from protobuf field <code>int64 enroll_date = 8;</code>
     * @param int|string $var
     * @return $this
     */
    public function setEnrollDate($var)
    {
        GPBUtil::checkInt64($var);
        $this->enroll_date = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 end_date = 9;</code>
     * @return int|string
     */
    public function getEndDate()
    {
        return $this->end_date;
    }

    /**
     * Generated from protobuf field <code>int64 end_date = 9;</code>
     * @param int|string $var
     * @return $this
     */
    public function setEndDate($var)
    {
        GPBUtil::checkInt64($var);
        $this->end_date = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 votecount = 10;</code>
     * @return int|string
     */
    public function getVotecount()
    {
        return $this->votecount;
    }

    /**
     * Generated from protobuf field <code>int64 votecount = 10;</code>
     * @param int|string $var
     * @return $this
     */
    public function setVotecount($var)
    {
        GPBUtil::checkInt64($var);
        $this->votecount = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 viewcount = 11;</code>
     * @return int|string
     */
    public function getViewcount()
    {
        return $this->viewcount;
    }

    /**
     * Generated from protobuf field <code>int64 viewcount = 11;</code>
     * @param int|string $var
     * @return $this
     */
    public function setViewcount($var)
    {
        GPBUtil::checkInt64($var);
        $this->viewcount = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 type = 12;</code>
     * @return int|string
     */
    public function getType()
    {
        return $this->type;
    }

    /**
     * Generated from protobuf field <code>int64 type = 12;</code>
     * @param int|string $var
     * @return $this
     */
    public function setType($var)
    {
        GPBUtil::checkInt64($var);
        $this->type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 num = 13;</code>
     * @return int|string
     */
    public function getNum()
    {
        return $this->num;
    }

    /**
     * Generated from protobuf field <code>int64 num = 13;</code>
     * @param int|string $var
     * @return $this
     */
    public function setNum($var)
    {
        GPBUtil::checkInt64($var);
        $this->num = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 enrollcount = 14;</code>
     * @return int|string
     */
    public function getEnrollcount()
    {
        return $this->enrollcount;
    }

    /**
     * Generated from protobuf field <code>int64 enrollcount = 14;</code>
     * @param int|string $var
     * @return $this
     */
    public function setEnrollcount($var)
    {
        GPBUtil::checkInt64($var);
        $this->enrollcount = $var;

        return $this;
    }

}

