<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: xindalu.proto

namespace Votes;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>votes.ArgsGetPayInfo</code>
 */
class ArgsGetPayInfo extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string OrderNo = 1;</code>
     */
    protected $OrderNo = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $OrderNo
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Xindalu::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string OrderNo = 1;</code>
     * @return string
     */
    public function getOrderNo()
    {
        return $this->OrderNo;
    }

    /**
     * Generated from protobuf field <code>string OrderNo = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setOrderNo($var)
    {
        GPBUtil::checkString($var, True);
        $this->OrderNo = $var;

        return $this;
    }

}

