<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: votes.proto

namespace Votes;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 *报名返回
 *
 * Generated from protobuf message <code>votes.EnrollResp</code>
 */
class EnrollResp extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int64 auid = 1;</code>
     */
    protected $auid = 0;
    /**
     * Generated from protobuf field <code>int64 beid = 2;</code>
     */
    protected $beid = 0;
    /**
     * Generated from protobuf field <code>int64 ptyid = 3;</code>
     */
    protected $ptyid = 0;
    /**
     * Generated from protobuf field <code>int64 uid = 4;</code>
     */
    protected $uid = 0;
    /**
     * Generated from protobuf field <code>string name = 5;</code>
     */
    protected $name = '';
    /**
     * Generated from protobuf field <code>string address = 6;</code>
     */
    protected $address = '';
    /**
     * Generated from protobuf field <code>repeated string images = 7;</code>
     */
    private $images;
    /**
     * Generated from protobuf field <code>string descr = 8;</code>
     */
    protected $descr = '';
    /**
     * Generated from protobuf field <code>int64 votecount = 9;</code>
     */
    protected $votecount = 0;
    /**
     * Generated from protobuf field <code>int64 viewcount = 10;</code>
     */
    protected $viewcount = 0;
    /**
     * Generated from protobuf field <code>int64 aeid = 11;</code>
     */
    protected $aeid = 0;
    /**
     * Generated from protobuf field <code>int64 actid = 12;</code>
     */
    protected $actid = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $auid
     *     @type int|string $beid
     *     @type int|string $ptyid
     *     @type int|string $uid
     *     @type string $name
     *     @type string $address
     *     @type string[]|\Google\Protobuf\Internal\RepeatedField $images
     *     @type string $descr
     *     @type int|string $votecount
     *     @type int|string $viewcount
     *     @type int|string $aeid
     *     @type int|string $actid
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Votes::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int64 auid = 1;</code>
     * @return int|string
     */
    public function getAuid()
    {
        return $this->auid;
    }

    /**
     * Generated from protobuf field <code>int64 auid = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setAuid($var)
    {
        GPBUtil::checkInt64($var);
        $this->auid = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 beid = 2;</code>
     * @return int|string
     */
    public function getBeid()
    {
        return $this->beid;
    }

    /**
     * Generated from protobuf field <code>int64 beid = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setBeid($var)
    {
        GPBUtil::checkInt64($var);
        $this->beid = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 ptyid = 3;</code>
     * @return int|string
     */
    public function getPtyid()
    {
        return $this->ptyid;
    }

    /**
     * Generated from protobuf field <code>int64 ptyid = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setPtyid($var)
    {
        GPBUtil::checkInt64($var);
        $this->ptyid = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 uid = 4;</code>
     * @return int|string
     */
    public function getUid()
    {
        return $this->uid;
    }

    /**
     * Generated from protobuf field <code>int64 uid = 4;</code>
     * @param int|string $var
     * @return $this
     */
    public function setUid($var)
    {
        GPBUtil::checkInt64($var);
        $this->uid = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string name = 5;</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Generated from protobuf field <code>string name = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string address = 6;</code>
     * @return string
     */
    public function getAddress()
    {
        return $this->address;
    }

    /**
     * Generated from protobuf field <code>string address = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setAddress($var)
    {
        GPBUtil::checkString($var, True);
        $this->address = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated string images = 7;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getImages()
    {
        return $this->images;
    }

    /**
     * Generated from protobuf field <code>repeated string images = 7;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setImages($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->images = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string descr = 8;</code>
     * @return string
     */
    public function getDescr()
    {
        return $this->descr;
    }

    /**
     * Generated from protobuf field <code>string descr = 8;</code>
     * @param string $var
     * @return $this
     */
    public function setDescr($var)
    {
        GPBUtil::checkString($var, True);
        $this->descr = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 votecount = 9;</code>
     * @return int|string
     */
    public function getVotecount()
    {
        return $this->votecount;
    }

    /**
     * Generated from protobuf field <code>int64 votecount = 9;</code>
     * @param int|string $var
     * @return $this
     */
    public function setVotecount($var)
    {
        GPBUtil::checkInt64($var);
        $this->votecount = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 viewcount = 10;</code>
     * @return int|string
     */
    public function getViewcount()
    {
        return $this->viewcount;
    }

    /**
     * Generated from protobuf field <code>int64 viewcount = 10;</code>
     * @param int|string $var
     * @return $this
     */
    public function setViewcount($var)
    {
        GPBUtil::checkInt64($var);
        $this->viewcount = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 aeid = 11;</code>
     * @return int|string
     */
    public function getAeid()
    {
        return $this->aeid;
    }

    /**
     * Generated from protobuf field <code>int64 aeid = 11;</code>
     * @param int|string $var
     * @return $this
     */
    public function setAeid($var)
    {
        GPBUtil::checkInt64($var);
        $this->aeid = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 actid = 12;</code>
     * @return int|string
     */
    public function getActid()
    {
        return $this->actid;
    }

    /**
     * Generated from protobuf field <code>int64 actid = 12;</code>
     * @param int|string $var
     * @return $this
     */
    public function setActid($var)
    {
        GPBUtil::checkInt64($var);
        $this->actid = $var;

        return $this;
    }

}

