<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: xindalu.proto

namespace Votes;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>votes.Pay</code>
 */
class Pay extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string OrderNo = 1;</code>
     */
    protected $OrderNo = '';
    /**
     * Generated from protobuf field <code>string PayTime = 2;</code>
     */
    protected $PayTime = '';
    /**
     * Generated from protobuf field <code>string PayStatus = 3;</code>
     */
    protected $PayStatus = '';
    /**
     * Generated from protobuf field <code>string BusId = 4;</code>
     */
    protected $BusId = '';
    /**
     * Generated from protobuf field <code>string CarId = 5;</code>
     */
    protected $CarId = '';
    /**
     * Generated from protobuf field <code>string Txamt = 6;</code>
     */
    protected $Txamt = '';
    /**
     * Generated from protobuf field <code>string OldTxamt = 7;</code>
     */
    protected $OldTxamt = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $OrderNo
     *     @type string $PayTime
     *     @type string $PayStatus
     *     @type string $BusId
     *     @type string $CarId
     *     @type string $Txamt
     *     @type string $OldTxamt
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Xindalu::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string OrderNo = 1;</code>
     * @return string
     */
    public function getOrderNo()
    {
        return $this->OrderNo;
    }

    /**
     * Generated from protobuf field <code>string OrderNo = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setOrderNo($var)
    {
        GPBUtil::checkString($var, True);
        $this->OrderNo = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string PayTime = 2;</code>
     * @return string
     */
    public function getPayTime()
    {
        return $this->PayTime;
    }

    /**
     * Generated from protobuf field <code>string PayTime = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setPayTime($var)
    {
        GPBUtil::checkString($var, True);
        $this->PayTime = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string PayStatus = 3;</code>
     * @return string
     */
    public function getPayStatus()
    {
        return $this->PayStatus;
    }

    /**
     * Generated from protobuf field <code>string PayStatus = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setPayStatus($var)
    {
        GPBUtil::checkString($var, True);
        $this->PayStatus = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string BusId = 4;</code>
     * @return string
     */
    public function getBusId()
    {
        return $this->BusId;
    }

    /**
     * Generated from protobuf field <code>string BusId = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setBusId($var)
    {
        GPBUtil::checkString($var, True);
        $this->BusId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string CarId = 5;</code>
     * @return string
     */
    public function getCarId()
    {
        return $this->CarId;
    }

    /**
     * Generated from protobuf field <code>string CarId = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setCarId($var)
    {
        GPBUtil::checkString($var, True);
        $this->CarId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string Txamt = 6;</code>
     * @return string
     */
    public function getTxamt()
    {
        return $this->Txamt;
    }

    /**
     * Generated from protobuf field <code>string Txamt = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setTxamt($var)
    {
        GPBUtil::checkString($var, True);
        $this->Txamt = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string OldTxamt = 7;</code>
     * @return string
     */
    public function getOldTxamt()
    {
        return $this->OldTxamt;
    }

    /**
     * Generated from protobuf field <code>string OldTxamt = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setOldTxamt($var)
    {
        GPBUtil::checkString($var, True);
        $this->OldTxamt = $var;

        return $this;
    }

}

