<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: xindalu.proto

namespace Votes;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>votes.ReplyGetPayinfo</code>
 */
class ReplyGetPayinfo extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.votes.Pay data = 1;</code>
     */
    protected $data = null;
    /**
     * Generated from protobuf field <code>string version = 2;</code>
     */
    protected $version = '';
    /**
     * Generated from protobuf field <code>.votes.Response res = 3;</code>
     */
    protected $res = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Votes\Pay $data
     *     @type string $version
     *     @type \Votes\Response $res
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Xindalu::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.votes.Pay data = 1;</code>
     * @return \Votes\Pay|null
     */
    public function getData()
    {
        return $this->data;
    }

    public function hasData()
    {
        return isset($this->data);
    }

    public function clearData()
    {
        unset($this->data);
    }

    /**
     * Generated from protobuf field <code>.votes.Pay data = 1;</code>
     * @param \Votes\Pay $var
     * @return $this
     */
    public function setData($var)
    {
        GPBUtil::checkMessage($var, \Votes\Pay::class);
        $this->data = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string version = 2;</code>
     * @return string
     */
    public function getVersion()
    {
        return $this->version;
    }

    /**
     * Generated from protobuf field <code>string version = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setVersion($var)
    {
        GPBUtil::checkString($var, True);
        $this->version = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.votes.Response res = 3;</code>
     * @return \Votes\Response|null
     */
    public function getRes()
    {
        return $this->res;
    }

    public function hasRes()
    {
        return isset($this->res);
    }

    public function clearRes()
    {
        unset($this->res);
    }

    /**
     * Generated from protobuf field <code>.votes.Response res = 3;</code>
     * @param \Votes\Response $var
     * @return $this
     */
    public function setRes($var)
    {
        GPBUtil::checkMessage($var, \Votes\Response::class);
        $this->res = $var;

        return $this;
    }

}

