<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: xindalu.proto

namespace Votes;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>votes.ReplyGetPayinfo</code>
 */
class ReplyGetPayinfo extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.votes.Pay data = 1;</code>
     */
    protected $data = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Votes\Pay $data
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Xindalu::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.votes.Pay data = 1;</code>
     * @return \Votes\Pay|null
     */
    public function getData()
    {
        return $this->data;
    }

    public function hasData()
    {
        return isset($this->data);
    }

    public function clearData()
    {
        unset($this->data);
    }

    /**
     * Generated from protobuf field <code>.votes.Pay data = 1;</code>
     * @param \Votes\Pay $var
     * @return $this
     */
    public function setData($var)
    {
        GPBUtil::checkMessage($var, \Votes\Pay::class);
        $this->data = $var;

        return $this;
    }

}

