<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: votes.proto

namespace Votes;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 *投票
 *
 * Generated from protobuf message <code>votes.VotesReq</code>
 */
class VotesReq extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int64 auid = 1;</code>
     */
    protected $auid = 0;
    /**
     * Generated from protobuf field <code>int64 beid = 2;</code>
     */
    protected $beid = 0;
    /**
     * Generated from protobuf field <code>int64 ptyid = 3;</code>
     */
    protected $ptyid = 0;
    /**
     * Generated from protobuf field <code>int64 uid = 4;</code>
     */
    protected $uid = 0;
    /**
     * Generated from protobuf field <code>int64 actid = 5;</code>
     */
    protected $actid = 0;
    /**
     * Generated from protobuf field <code>int64 aeid = 6;</code>
     */
    protected $aeid = 0;
    /**
     * Generated from protobuf field <code>string ip = 7;</code>
     */
    protected $ip = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $auid
     *     @type int|string $beid
     *     @type int|string $ptyid
     *     @type int|string $uid
     *     @type int|string $actid
     *     @type int|string $aeid
     *     @type string $ip
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Votes::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int64 auid = 1;</code>
     * @return int|string
     */
    public function getAuid()
    {
        return $this->auid;
    }

    /**
     * Generated from protobuf field <code>int64 auid = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setAuid($var)
    {
        GPBUtil::checkInt64($var);
        $this->auid = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 beid = 2;</code>
     * @return int|string
     */
    public function getBeid()
    {
        return $this->beid;
    }

    /**
     * Generated from protobuf field <code>int64 beid = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setBeid($var)
    {
        GPBUtil::checkInt64($var);
        $this->beid = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 ptyid = 3;</code>
     * @return int|string
     */
    public function getPtyid()
    {
        return $this->ptyid;
    }

    /**
     * Generated from protobuf field <code>int64 ptyid = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setPtyid($var)
    {
        GPBUtil::checkInt64($var);
        $this->ptyid = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 uid = 4;</code>
     * @return int|string
     */
    public function getUid()
    {
        return $this->uid;
    }

    /**
     * Generated from protobuf field <code>int64 uid = 4;</code>
     * @param int|string $var
     * @return $this
     */
    public function setUid($var)
    {
        GPBUtil::checkInt64($var);
        $this->uid = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 actid = 5;</code>
     * @return int|string
     */
    public function getActid()
    {
        return $this->actid;
    }

    /**
     * Generated from protobuf field <code>int64 actid = 5;</code>
     * @param int|string $var
     * @return $this
     */
    public function setActid($var)
    {
        GPBUtil::checkInt64($var);
        $this->actid = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 aeid = 6;</code>
     * @return int|string
     */
    public function getAeid()
    {
        return $this->aeid;
    }

    /**
     * Generated from protobuf field <code>int64 aeid = 6;</code>
     * @param int|string $var
     * @return $this
     */
    public function setAeid($var)
    {
        GPBUtil::checkInt64($var);
        $this->aeid = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string ip = 7;</code>
     * @return string
     */
    public function getIp()
    {
        return $this->ip;
    }

    /**
     * Generated from protobuf field <code>string ip = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setIp($var)
    {
        GPBUtil::checkString($var, True);
        $this->ip = $var;

        return $this;
    }

}

